### PR TITLE
renaming

### PR DESCRIPTION
**Pull request by DNaunin**
Renaming pages and css files (Loading screen and Index page were swapped, now made the naming consistent)
Better CSS Code, some renaming and shortening

### CODE REVIEW

**Review by JuKahl — APPROVED** [review]
LGTM 🧸

**Review by RonjaMeinecke — APPROVED** [review]
🧼🧼🧼🧼🧼well done

**Comment by RonjaMeinecke** [comment]
just had a look at the deployment now, such a good job! 💄✨

**Review by cboenke — APPROVED** [review]
GJ! 🚀

**Review by m-wiemers — COMMENTED** [review]
lvgtm 🚀

**Pull request merged**
